### ISSUE TITLE
Java.Lang.NullPointerException: null reference

### ISSUE THREAD

**Issue by PrathamsGithub** [shinyorg/Health#1]
I have added this package version (1.0.0-beta-0021) in my code and added the below code but I am getting null reference exception on   

`Distance = (await _HealthService.GetDistances(start, end, Interval.Hours)).LastOrDefault().Value;`

Whole code

`StartDate = DateTime.Now.AddDays(-1);
            EndDate = DateTime.Now;
            var start = StartDate.Date.Add(new TimeSpan(0, 0, 0));
            var currenttime = TimeSpan.Parse(DateTime.Now.ToString("HH:mm:ss"));
            var end = EndDate.Date.Add(currenttime);
            var result = await _HealthService.RequestPermissions(
                            DataType.Calories,
                            DataType.Distance,
                            DataType.HeartRate,
                            DataType.StepCount
                        );
            Distance = (await _HealthService.GetDistances(start, end, Interval.Hours)).LastOrDefault().Value;
            Calories = (await _HealthService.GetCalories(start, end, Interval.Hours)).LastOrDefault().Value;`

**Comment by aritchie** [comment]
I'm sorry.  I'm not supporting previews at this time.  This may never be finished due to binding issues going on with the new AndroidX health client
